name: Build container image
description: Build and push container image from Dockerfile with cache
inputs:
  image:
    description: The image name
    required: true
  tag:
    description: The tag on the image
    required: true
  context:
    description: Path to the build context
    default: "."
    required: true
  dockerfile:
    description: "Path to the dockerfile"
    default: "Dockerfile"
    required: true
  github_token:
    description: "Github token"
    required: true

runs:
  using: composite
  steps:
    - name: Login to docker registyr
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and Push container image
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: true
        tags: "ghcr.io/${{ github.repository_owner }}/${{ inputs.image }}:${{ inputs.tag }}${{ (github.ref == 'main' && format(',ghcr.io/{0}/{1}:latest', github.repository_owner, inputs.image)) || '' }}"
        cache-from: "type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ inputs.image }}:buildcache"
        cache-to: "${{ (github.ref == 'main' && format('type=registry,ref=ghcr.io/{0}/{1}:buildcache,mode=max', github.repository_owner, inputs.image)) || '' }}"
